/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    clients: Client;
    apps: App;
    skills: Skill;
    experience: Experience;
    education: Education;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    apps: AppsSelect<false> | AppsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'personal-info': PersonalInfo;
    'site-settings': SiteSettings;
  };
  globalsSelect: {
    'personal-info': PersonalInfoSelect<false> | PersonalInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}

export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}

export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}

export interface Project {
  id: number;
  name: string;
  slug: string;
  type?: string | null;
  description: string;
  date?: string | null;
  location?: string | null;
  url?: string | null;
  featured?: boolean | null;
  color?: string | null;
  image?: (number | null) | Media;
  imageUrl?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  password?: string | null;
  details?: {
    client?: string | null;
    duration?: string | null;
    team?: string | null;
    role?: string | null;
    challenge?: string | null;
    solution?: string | null;
    impact?: string | null;
    sections?:
      | {
          title: string;
          content?: Record<string, unknown> | null;
          images?:
            | {
                image?: (number | null) | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    testimonial?: {
      quote?: string | null;
      author?: string | null;
      role?: string | null;
    };
    nextProject?: (number | null) | Project;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Client {
  id: number;
  name: string;
  url?: string | null;
  logo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface App {
  id: number;
  name: string;
  slug: string;
  icon?: (number | null) | Media;
  iconUrl?: string | null;
  description: string;
  appStoreUrl?: string | null;
  playStoreUrl?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  color?: string | null;
  featured?: boolean | null;
  details?: {
    category?: string | null;
    platform?: string | null;
    downloads?: string | null;
    rating?: string | null;
    releaseDate?: string | null;
    version?: string | null;
    overview?: Record<string, unknown> | null;
    features?:
      | {
          feature?: string | null;
          id?: string | null;
        }[]
      | null;
    screenshots?:
      | {
          screenshot?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    testimonials?:
      | {
          quote?: string | null;
          author?: string | null;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Skill {
  id: number;
  name: string;
  category?: ('design' | 'development' | 'tools' | 'soft-skills' | 'other') | null;
  proficiency?: ('expert' | 'advanced' | 'intermediate' | 'beginner') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface Experience {
  id: number;
  title: string;
  company: string;
  companyUrl?: string | null;
  period: string;
  description?: Record<string, unknown> | null;
  projects?:
    | {
        project?: Record<string, unknown> | null;
        id?: string | null;
      }[]
    | null;
  recommendation?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
    date?: string | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface Education {
  id: number;
  degree: string;
  school: string;
  schoolUrl?: string | null;
  year: string;
  description?: Record<string, unknown> | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface PersonalInfo {
  id: number;
  name: string;
  firstName: string;
  lastName: string;
  title: string;
  subtitle?: string | null;
  status?: string | null;
  studio?: string | null;
  location?: string | null;
  email: string;
  phone?: string | null;
  website?: string | null;
  bio: Record<string, unknown>;
  avatar?: (number | null) | Media;
  tools?:
    | {
        tool?: string | null;
        id?: string | null;
      }[]
    | null;
  roles?:
    | {
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  experience?: string | null;
  keyContributions?:
    | {
        contribution?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    linkedin?: string | null;
    github?: string | null;
    medium?: string | null;
    twitter?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface SiteSettings {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  siteKeywords?: string | null;
  ogImage?: (number | null) | Media;
  favicon?: (number | null) | Media;
  analytics?: {
    googleAnalytics?: string | null;
    posthogKey?: string | null;
    posthogHost?: string | null;
  };
  maintenance?: {
    enabled?: boolean | null;
    message?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}

export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'apps';
        value: number | App;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}

export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}

export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}

export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  date?: T;
  location?: T;
  url?: T;
  featured?: T;
  color?: T;
  image?: T;
  imageUrl?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  password?: T;
  details?:
    | T
    | {
        client?: T;
        duration?: T;
        team?: T;
        role?: T;
        challenge?: T;
        solution?: T;
        impact?: T;
        sections?:
          | T
          | {
              title?: T;
              content?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
        testimonial?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
            };
        nextProject?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}

export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface AppsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  iconUrl?: T;
  description?: T;
  appStoreUrl?: T;
  playStoreUrl?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  color?: T;
  featured?: T;
  details?:
    | T
    | {
        category?: T;
        platform?: T;
        downloads?: T;
        rating?: T;
        releaseDate?: T;
        version?: T;
        overview?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        screenshots?:
          | T
          | {
              screenshot?: T;
              id?: T;
            };
        testimonials?:
          | T
          | {
              quote?: T;
              author?: T;
              rating?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}

export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  proficiency?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface ExperienceSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  companyUrl?: T;
  period?: T;
  description?: T;
  projects?:
    | T
    | {
        project?: T;
        id?: T;
      };
  recommendation?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        date?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface EducationSelect<T extends boolean = true> {
  degree?: T;
  school?: T;
  schoolUrl?: T;
  year?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface PersonalInfoSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  title?: T;
  subtitle?: T;
  status?: T;
  studio?: T;
  location?: T;
  email?: T;
  phone?: T;
  website?: T;
  bio?: T;
  avatar?: T;
  tools?:
    | T
    | {
        tool?: T;
        id?: T;
      };
  roles?:
    | T
    | {
        role?: T;
        id?: T;
      };
  experience?: T;
  keyContributions?:
    | T
    | {
        contribution?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        linkedin?: T;
        github?: T;
        medium?: T;
        twitter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}

export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  siteKeywords?: T;
  ogImage?: T;
  favicon?: T;
  analytics?:
    | T
    | {
        googleAnalytics?: T;
        posthogKey?: T;
        posthogHost?: T;
      };
  maintenance?:
    | T
    | {
        enabled?: T;
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}

export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}

export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
