/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: Record<string, never>;
  collections: {
    users: User;
    media: Media;
    projects: Project;
    clients: Client;
    apps: App;
    skills: Skill;
    experience: Experience;
    education: Education;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: Record<string, never>;
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    apps: AppsSelect<false> | AppsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'personal-info': PersonalInfo;
    'site-settings': SiteSettings;
  };
  globalsSelect: {
    'personal-info': PersonalInfoSelect<false> | PersonalInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}

export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}

export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
}

export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}

export interface Project {
  id: number;
  name: string;
  slug: string;
  type?: string | null;
  description: string;
  date?: string | null;
  location?: string | null;
  url?: string | null;
  featured?: boolean | null;
  color?: string | null;
  image?: number | Media | null;
  imageUrl?: string | null;
  tags?: Array<{ tag?: string | null; id?: string | null }> | null;
  password?: string | null;
  details?: {
    client?: string | null;
    duration?: string | null;
    team?: string | null;
    role?: string | null;
    challenge?: string | null;
    solution?: string | null;
    impact?: string | null;
    sections?:
      | Array<{
          title: string;
          content?: unknown;
          images?: Array<{ image?: number | Media | null; id?: string | null }> | null;
          id?: string | null;
        }>
      | null;
    testimonial?: {
      quote?: string | null;
      author?: string | null;
      role?: string | null;
    };
    nextProject?: number | Project | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Client {
  id: number;
  name: string;
  url?: string | null;
  logo?: number | Media | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface App {
  id: number;
  name: string;
  slug: string;
  icon?: number | Media | null;
  iconUrl?: string | null;
  description: string;
  appStoreUrl?: string | null;
  playStoreUrl?: string | null;
  tags?: Array<{ tag?: string | null; id?: string | null }> | null;
  color?: string | null;
  featured?: boolean | null;
  details?: {
    category?: string | null;
    platform?: string | null;
    downloads?: string | null;
    rating?: string | null;
    releaseDate?: string | null;
    version?: string | null;
    overview?: unknown;
    features?: Array<{ feature?: string | null; id?: string | null }> | null;
    screenshots?: Array<{ screenshot?: number | Media | null; id?: string | null }> | null;
    testimonials?: Array<{
      quote?: string | null;
      author?: string | null;
      rating?: number | null;
      id?: string | null;
    }> | null;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Skill {
  id: number;
  name: string;
  category?: 'design' | 'development' | 'tools' | 'soft-skills' | 'other' | null;
  proficiency?: 'expert' | 'advanced' | 'intermediate' | 'beginner' | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface Experience {
  id: number;
  title: string;
  company: string;
  companyUrl?: string | null;
  period: string;
  description?: unknown;
  projects?: Array<{ project?: unknown; id?: string | null }> | null;
  recommendation?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
    date?: string | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface Education {
  id: number;
  degree: string;
  school: string;
  schoolUrl?: string | null;
  year: string;
  description?: unknown;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface PersonalInfo {
  id: number;
  name: string;
  firstName: string;
  lastName: string;
  title: string;
  subtitle?: string | null;
  status?: string | null;
  studio?: string | null;
  location?: string | null;
  email: string;
  phone?: string | null;
  website?: string | null;
  bio?: unknown;
  avatar?: number | Media | null;
  tools?: Array<{ tool?: string | null; id?: string | null }> | null;
  roles?: Array<{ role?: string | null; id?: string | null }> | null;
  experience?: string | null;
  keyContributions?: Array<{ contribution?: string | null; id?: string | null }> | null;
  socialLinks?: {
    linkedin?: string | null;
    github?: string | null;
    medium?: string | null;
    twitter?: string | null;
  };
  updatedAt?: string;
  createdAt?: string;
  globalType?: string;
}

export interface SiteSettings {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  siteKeywords?: string | null;
  ogImage?: number | Media | null;
  favicon?: number | Media | null;
  analytics?: {
    googleAnalytics?: string | null;
    posthogKey?: string | null;
    posthogHost?: string | null;
  };
  maintenance?: {
    enabled?: boolean | null;
    message?: string | null;
  };
  updatedAt?: string;
  createdAt?: string;
  globalType?: string;
}

// ─── Payload internal types ───────────────────────────────────────────────────

export interface PayloadKv {
  id: number;
  key: string;
  data: unknown;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadLockedDocument {
  id: number;
  document?: { relationTo: string; value: number | Record<string, unknown> } | null;
  globalSlug?: string | null;
  user: { relationTo: 'users'; value: number | User };
  updatedAt: string;
  createdAt: string;
}

export interface PayloadPreference {
  id: number;
  user: { relationTo: 'users'; value: number | User };
  key?: string | null;
  value?: unknown;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

// ─── Select types ─────────────────────────────────────────────────────────────

export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
}

export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  filename?: T;
}

export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  date?: T;
  location?: T;
  url?: T;
  featured?: T;
  color?: T;
  image?: T;
  imageUrl?: T;
  tags?: T;
  password?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface AppsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  iconUrl?: T;
  description?: T;
  appStoreUrl?: T;
  playStoreUrl?: T;
  tags?: T;
  color?: T;
  featured?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  proficiency?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface ExperienceSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  companyUrl?: T;
  period?: T;
  description?: T;
  projects?: T;
  recommendation?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface EducationSelect<T extends boolean = true> {
  degree?: T;
  school?: T;
  schoolUrl?: T;
  year?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface PersonalInfoSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  title?: T;
  subtitle?: T;
  status?: T;
  studio?: T;
  location?: T;
  email?: T;
  phone?: T;
  website?: T;
  bio?: T;
  avatar?: T;
  tools?: T;
  roles?: T;
  experience?: T;
  keyContributions?: T;
  socialLinks?: T;
}

export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  siteKeywords?: T;
  ogImage?: T;
  favicon?: T;
  analytics?: T;
  maintenance?: T;
}

export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}

export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}

export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
